[versions]
agp = "8.10.1"
coreKtx = "1.15.0"
gson = "2.13.1"
kotlin = "2.2.0"
tunnel = "1.0.20230706"
coroutine = "1.10.2"
activityKtx = "1.10.1"
appcompat = "1.7.1"
[libraries]
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
tunnel = { module = "com.wireguard.android:tunnel", version.ref = "tunnel" }
coroutine = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutine" }
activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityKtx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
maven = {id = "maven-publish"}
android-library = { id = "com.android.library", version.ref = "agp" }

